In [ ]:
#### MODULE 8 #### JSON FILE IMPORT ####

In [8]:
import json
import pandas as pd
import numpy as np

# import regular expressions 
import re

In [9]:
file_dir = "C:/Users/15124/Desktop/Class_work/"
# "C:\Users\15124\Desktop\Class_work\Movies-ETL\wikipedia-movies.json"

In [10]:
#### 8.2.1 #### 8.2.1#### 8.2.1#### 8.2.1#### 8.2.1#### 8.2.1#### 8.2.1
file_dir

'C:/Users/15124/Desktop/Class_work/'

In [11]:
# Using the *with* statement, open the wikipedia JSON file to be read into variable *file*
# and use the *json.load() to save the data to a new variable.

with open(f'{file_dir}wikipedia-movies.json', mode = "r") as file:
          wiki_movies_raw = json.load(file)

In [12]:
len(wiki_movies_raw)

7311

In [43]:
# checking first 5 records- b/c we're working with a list and NOT a dataframe
# GOTTA USE INDEX SLICE

wiki_movies_raw[:5]

[{'url': 'https://en.wikipedia.org/wiki/The_Adventures_of_Ford_Fairlane',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0098987/',
  'title': 'The Adventures of Ford Fairlane',
  'Directed by': 'Renny Harlin',
  'Produced by': ['Steve Perry', 'Joel Silver'],
  'Screenplay by': ['David Arnott', 'James Cappe', 'Daniel Waters'],
  'Story by': ['David Arnott', 'James Cappe'],
  'Based on': ['Characters', 'by Rex Weiner'],
  'Starring': ['Andrew Dice Clay',
   'Wayne Newton',
   'Priscilla Presley',
   'Lauren Holly',
   'Morris Day',
   'Robert Englund',
   "Ed O'Neill"],
  'Narrated by': 'Andrew "Dice" Clay',
  'Music by': ['Cliff Eidelman', 'Yello'],
  'Cinematography': 'Oliver Wood',
  'Edited by': 'Michael Tronick',
  'Productioncompany ': 'Silver Pictures',
  'Distributed by': '20th Century Fox',
  'Release date': ['July 11, 1990', '(', '1990-07-11', ')'],
  'Running time': '102 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$21.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/After_Dark,_My_Sweet',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0098994/',
  'title': 'After Dark, My Sweet',
  'Directed by': 'James Foley',
  'Produced by': ['Ric Kidney', 'Robert Redlin'],
  'Screenplay by': ['James Foley', 'Robert Redlin'],
  'Based on': ['the novel', 'After Dark, My Sweet', 'by', 'Jim Thompson'],
  'Starring': ['Jason Patric',
   'Rachel Ward',
   'Bruce Dern',
   'George Dickerson'],
  'Music by': 'Maurice Jarre',
  'Cinematography': 'Mark Plummer',
  'Edited by': 'Howard E. Smith',
  'Productioncompany ': 'Avenue Pictures',
  'Distributed by': 'Avenue Pictures',
  'Release date': ['May 17, 1990',
   '(',
   '1990-05-17',
   ')',
   '(Cannes Film Market)',
   'August 24, 1990',
   '(',
   '1990-08-24',
   ')',
   '(United States)'],
  'Running time': '114 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$6 million',
  'Box office': '$2.7 million'},
 {'url': 'https://en.wikipedia.org/wiki/Air_America_(film)',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099005/',
  'title': 'Air America',
  'Directed by': 'Roger Spottiswoode',
  'Produced by': 'Daniel Melnick',
  'Screenplay by': ['John Eskow', 'Richard Rush'],
  'Based on': ['Air America', 'by', 'Christopher Robbins'],
  'Starring': ['Mel Gibson',
   'Robert Downey Jr.',
   'Nancy Travis',
   'David Marshall Grant',
   'Lane Smith'],
  'Music by': 'Charles Gross',
  'Cinematography': 'Roger Deakins',
  'Edited by': ['John Bloom', 'Lois Freeman-Fox'],
  'Productioncompany ': ['Carolco Pictures', 'IndieProd Company'],
  'Distributed by': 'TriStar Pictures',
  'Release date': ['August 10, 1990', '(', '1990-08-10', ')'],
  'Running time': '113 minutes',
  'Country': 'United States',
  'Language': ['English', 'Lao'],
  'Budget': '$35 million',
  'Box office': '$57,718,089'},
 {'url': 'https://en.wikipedia.org/wiki/Alice_(1990_film)',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099012/',
  'title': 'Alice',
  'Directed by': 'Woody Allen',
  'Produced by': 'Robert Greenhut',
  'Written by': 'Woody Allen',
  'Starring': ['Alec Baldwin',
   'Blythe Danner',
   'Judy Davis',
   'Mia Farrow',
   'William Hurt',
   'Keye Luke',
   'Joe Mantegna',
   'Bernadette Peters'],
  'Cinematography': 'Carlo Di Palma',
  'Edited by': 'Susan E. Morse',
  'Distributed by': 'Orion Pictures',
  'Release date': ['December 25, 1990', '(', '1990-12-25', ')'],
  'Running time': '106 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$12 million',
  'Box office': '$7,331,647'},
 {'url': 'https://en.wikipedia.org/wiki/Almost_an_Angel',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099018/',
  'title': 'Almost an Angel',
  'Directed by': 'John Cornell',
  'Produced by': 'John Cornell',
  'Written by': 'Paul Hogan',
  'Starring': ['Paul Hogan', 'Elias Koteas', 'Linda Kozlowski'],
  'Music by': 'Maurice Jarre',
  'Cinematography': 'Russell Boyd',
  'Edited by': 'David Stiven',
  'Distributed by': 'Paramount Pictures',
  'Release date': 'December 19, 1990',
  'Running time': '95 minutes',
  'Country': 'US',
  'Language': 'English',
  'Budget': '$25 million',
  'Box office': '$6,939,946 (USA)'}]

In [44]:
# check the last 5 records using INDEX SLICING (b/c its list)

wiki_movies_raw[-5:]

[{'url': 'https://en.wikipedia.org/wiki/Holmes_%26_Watson',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt1255919/',
  'title': 'Holmes & Watson',
  'Directed by': 'Etan Cohen',
  'Produced by': ['Will Ferrell',
   'Adam McKay',
   'Jimmy Miller',
   'Clayton Townsend'],
  'Screenplay by': 'Etan Cohen',
  'Based on': ['Sherlock Holmes',
   'and',
   'Dr. Watson',
   'by',
   'Sir Arthur Conan Doyle'],
  'Starring': ['Will Ferrell',
   'John C. Reilly',
   'Rebecca Hall',
   'Rob Brydon',
   'Steve Coogan',
   'Ralph Fiennes'],
  'Music by': 'Mark Mothersbaugh',
  'Cinematography': 'Oliver Wood',
  'Edited by': 'Dean Zimmerman',
  'Productioncompanies ': ['Columbia Pictures',
   'Gary Sanchez Productions',
   'Mosaic Media Group',
   'Mimran Schur Pictures'],
  'Distributed by': 'Sony Pictures Releasing',
  'Release date': ['December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '90 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$42 million',
  'Box office': '$41.9 million'},
 {'url': 'https://en.wikipedia.org/wiki/Vice_(2018_film)',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt6266538/',
  'title': 'Vice',
  'Directed by': 'Adam McKay',
  'Produced by': ['Brad Pitt',
   'Dede Gardner',
   'Jeremy Kleiner',
   'Kevin J. Messick',
   'Will Ferrell',
   'Adam McKay'],
  'Written by': 'Adam McKay',
  'Starring': ['Christian Bale',
   'Amy Adams',
   'Steve Carell',
   'Sam Rockwell',
   'Tyler Perry',
   'Alison Pill',
   'Lily Rabe',
   'Jesse Plemons'],
  'Music by': 'Nicholas Britell',
  'Cinematography': 'Greig Fraser',
  'Edited by': 'Hank Corwin',
  'Productioncompany ': ['Plan B Entertainment',
   'Gary Sanchez Productions',
   'Annapurna Pictures'],
  'Distributed by': 'Mirror Releasing',
  'Release date': ['December 11, 2018',
   '(',
   '2018-12-11',
   ')',
   '(',
   'Samuel Goldwyn Theater',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '132 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$60 million',
  'Box office': '$76.1 million'},
 {'url': 'https://en.wikipedia.org/wiki/On_the_Basis_of_Sex',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt4669788/',
  'title': 'On the Basis of Sex',
  'Directed by': 'Mimi Leder',
  'Produced by': 'Robert W. Cort',
  'Written by': 'Daniel Stiepleman',
  'Starring': ['Felicity Jones',
   'Armie Hammer',
   'Justin Theroux',
   'Sam Waterston',
   'Kathy Bates'],
  'Music by': 'Mychael Danna',
  'Cinematography': 'Michael Grady',
  'Edited by': 'Michelle Tesoro',
  'Productioncompanies ': ['Focus Features',
   '[1]',
   'Participant Media',
   '[1]',
   'Robert Cort Productions',
   '[1]',
   'Alibaba Pictures',
   '[2]'],
  'Distributed by': 'Focus Features',
  'Release date': ['November 8, 2018',
   '(',
   '2018-11-08',
   ')',
   '(',
   'AFI Fest',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '120 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$38.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/Destroyer_(2018_film)',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt7137380/',
  'title': 'Destroyer',
  'Directed by': 'Karyn Kusama',
  'Produced by': ['Fred Berger', 'Phil Hay', 'Matt Manfredi'],
  'Written by': ['Phil Hay', 'Matt Manfredi'],
  'Starring': ['Nicole Kidman',
   'Sebastian Stan',
   'Toby Kebbell',
   'Tatiana Maslany',
   'Bradley Whitford',
   'Jade Pettyjohn',
   'Scoot McNairy'],
  'Music by': 'Theodore Shapiro',
  'Cinematography': 'Julie Kirkwood',
  'Edited by': 'Plummy Tucker',
  'Productioncompany ': ['30West',
   'Automatik Entertainment',
   'Annapurna Pictures'],
  'Distributed by': 'Mirror Releasing',
  'Release date': ['August 31, 2018',
   '(',
   '2018-08-31',
   ')',
   '(',
   'Telluride',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '123 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$9 million',
  'Box office': '$5.5 million'},
 {'url': 'https://en.wikipedia.org/wiki/Black_Mirror:_Bandersnatch',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt9495224/',
  'title': 'Bandersnatch',
  'Directed by': 'David Slade',
  'Produced by': 'Russell McLean',
  'Written by': 'Charlie Brooker',
  'Starring': ['Fionn Whitehead',
   'Will Poulter',
   'Craig Parkinson',
   'Alice Lowe',
   'Asim Chaudhry'],
  'Music by': 'Brian Reitzell',
  'Cinematography': ['Aaron Morton', 'Jake Polonsky'],
  'Edited by': 'Tony Kearns',
  'Productioncompany ': ['House of Tomorrow', 'Netflix'],
  'Distributed by': 'Netflix',
  'Release date': ['28 December 2018', '(', '2018-12-28', ')'],
  'Running time': 'Variable; 90 minutes for default path',
  'Country': 'United Kingdom',
  'Language': 'English'}]

In [45]:
# Checking random middle part of JSON with INDEX SLICE

wiki_movies_raw[3400: 3405]

[{'url': 'https://en.wikipedia.org/wiki/Charlie%27s_Angels:_Full_Throttle',
  'year': 2003,
  'imdb_link': 'https://www.imdb.com/title/tt0305357/',
  'title': "Charlie's Angels: Full Throttle",
  'Directed by': 'McG',
  'Produced by': ['Drew Barrymore', 'Leonard Goldberg', 'Nancy Juvonen'],
  'Screenplay by': ['John August', 'Cormac Wibberley', 'Marianne Wibberley'],
  'Story by': 'John August',
  'Based on': ["Charlie's Angels", 'by', 'Ivan Goff', 'Ben Roberts'],
  'Starring': ['Cameron Diaz',
   'Drew Barrymore',
   'Lucy Liu',
   'Bernie Mac',
   'Crispin Glover',
   'Justin Theroux',
   'Robert Patrick',
   'Demi Moore'],
  'Narrated by': 'John Forsythe',
  'Music by': 'Edward Shearmur',
  'Cinematography': 'Russell Carpenter',
  'Edited by': 'Wayne Wahrman',
  'Productioncompanies ': ['Wonderland Sound and Vision',
   'Flower Films',
   'Tall Trees Productions'],
  'Distributed by': 'Columbia Pictures',
  'Release date': ['June 27, 2003', '(', '2003-06-27', ')'],
  'Running time': '106 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$120 million',
  'Box office': '$259.1 million'},
 {'url': 'https://en.wikipedia.org/wiki/Chasing_Papi',
  'year': 2003,
  'imdb_link': 'https://www.imdb.com/title/tt0323572/',
  'title': 'Chasing Papi',
  'Directed by': 'Linda Mendoza',
  'Produced by': ['Laura Angelica Simon', 'Tracey Trench', 'Forest Whitaker'],
  'Written by': ['Laura Angelica Simon', 'Steve Antin'],
  'Starring': ['Roselyn Sánchez',
   'Sofía Vergara',
   'Jaci Velasquez',
   'Eduardo Verástegui'],
  'Music by': 'Emilio Estefan',
  'Cinematography': 'Xavier Pérez Grobet',
  'Edited by': 'Maysie Hoy',
  'Productioncompany ': ['Robert Simonds Productions',
   'Spirit Dance Entertainment',
   'Fox 2000 Pictures'],
  'Distributed by': '20th Century Fox',
  'Release date': 'April 16, 2003',
  'Running time': '80 minutes',
  'Country': 'United States',
  'Language': ['English', 'Spanish'],
  'Budget': '$9,000,000 USD',
  'Box office': '$12.6 million'},
 {'url': 'https://en.wikipedia.org/wiki/Cheaper_by_the_Dozen_(2003_film)',
  'year': 2003,
  'imdb_link': 'https://www.imdb.com/title/tt0349205/',
  'title': 'Cheaper by the Dozen',
  'Directed by': 'Shawn Levy',
  'Produced by': ['Robert Simonds', 'Michael Barnathan', 'Ben Myron'],
  'Screenplay by': ['Sam Harper', 'Joel Cohen', 'Alec Sokolow'],
  'Story by': 'Craig Titley',
  'Based on': ['Cheaper by the Dozen',
   'by',
   'Frank B. Gilbreth, Jr.',
   'Ernestine Gilbreth Carey'],
  'Starring': ['Steve Martin',
   'Bonnie Hunt',
   'Hilary Duff',
   'Tom Welling',
   'Piper Perabo',
   'Ashton Kutcher',
   'Richard Jenkins',
   'Alyson Stoner',
   'Forrest Landis'],
  'Narrated by': 'Bonnie Hunt',
  'Music by': 'Christophe Beck',
  'Cinematography': 'Jonathan Brown',
  'Edited by': 'George Folsey, Jr.',
  'Productioncompany ': 'Robert Simonds Productions',
  'Distributed by': '20th Century Fox',
  'Release date': ['December 25, 2003',
   '(',
   '2003-12-25',
   ')',
   '(United States)'],
  'Running time': '98 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$40 million',
  'Box office': '$190.2 million'},
 {'url': 'https://en.wikipedia.org/wiki/Christmas_Child',
  'year': 2003,
  'imdb_link': 'https://www.imdb.com/title/tt0346750/',
  'title': 'Christmas Child',
  'Directed by': 'William Ewing',
  'Written by': ['Andrea Jobe', 'Eric Newman'],
  'Starring': ['Steven Curtis Chapman',
   'William R. Moses',
   'Megan Follows',
   'Vicki Taylor Ross',
   'Dennis Letts',
   'Grant James'],
  'Release date': ['November 9, 2004', '(', '2004-11-09', ')'],
  'Running time': '96 minutes',
  'Country': 'United States',
  'Language': 'English'},
 {'url': 'https://en.wikipedia.org/wiki/Coffee_and_Cigarettes',
  'year': 2003,
  'imdb_link': 'https://www.imdb.com/title/tt0379217/',
  'title': 'Coffee and Cigarettes',
  'Directed by': 'Jim Jarmusch',
  'Produced by': ['Jason Kliot',
   'Rudd Simmons',
   'Jim Stark',
   'Birgit Staudt',
   'Joana Vicente'],
  'Written by': 'Jim Jarmusch',
  'Starring': ['Roberto Benigni',
   'Steven Wright',
   'Joie Lee',
   'Cinqué Lee',
   'Steve Buscemi',
   'Iggy Pop',
   'Tom Waits',
   'Joseph Rigano',
   'Vinny Vella',
   'Vinny Vella Jr.',
   'E.J. Rodriguez',
   'Alex Descas',
   'Isaach De Bankolé',
   'Cate Blanchett',
   'Meg White',
   'Jack White',
   'Alfred Molina',
   'Steve Coogan',
   'GZA',
   'RZA',
   'Bill Murray',
   'William Rice',
   'Taylor Mead'],
  'Cinematography': ['Frederick Elmes',
   'ASC',
   'Ellen Kuras',
   'ASC',
   'Robby Müller',
   'Tom Dicillo'],
  'Edited by': ['Jay Rabinowitz',
   'ACE',
   'Melody London',
   'Terry Kats',
   'Jim Jarmusch'],
  'Distributed by': 'MGM Distribution Co.',
  'Release date': 'May 14, 2004',
  'Running time': '95 minutes',
  'Country': 'USA, Japan, Italy',
  'Language': ['English', 'French'],
  'Box office': '$7.9 million'}]

In [ ]:
#### EXTRACTION OF JSON COMPLETE, ONTO THE KAGGLE DATA ####

In [ ]:
##### 8.2.2 ##### EXTRACT KAGGLE DATA ##### 8.2.2 ##### EXTRACT KAGGLE DATA

In [13]:
# Just want the movies_metadata.csv and the ratings.csv files
kaggle_metadata = pd.read_csv(f'{file_dir}movies_metadata.csv')

C:\Users\15124\anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [14]:
ratings = pd.read_csv(f'{file_dir}ratings.csv')

In [49]:
ratings.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [15]:
kaggle_metadata.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [16]:
# Skill drill note- good idea to sample random entries into the DF at the beginning.
# use sample() method to do so.  

ratings.sample(n=5)

          userId  movieId  rating   timestamp
22830845  237233      588     3.0   840758447
12214424  126713     3755     3.5  1295411173
544720      5602     2291     3.0   974642960
2447144    25415      552     3.0   953768071
11309479  117338     5952     2.5  1457272896

In [ ]:
### 8.3.1 ### TRANSFORM DATA
# INSPECT, PLAN, EXECUTE cycle

# Early iterations through the transform phase look to handle big chunks of data at one time
# while later iterations work to fine tune smaller chunks that need to be worked on

# Two ways to modify our data

# 1. ) modify values
# includes removing rows or columns, replacing values, or generating new columns from old ones. 
# Converting a column to a new data type is also a form of replacing values.


# 2. ) modify structure 
# includes pivoting the values of one column into multiple columns, aggregating rows, and merging multiple data sets.
# Can also include aggreating large amounts of data into summary data or summary stats.


# after implmenenting whatever changes you decide on, NEXT STEP is to return and INSPECT the data
# in a *new iteration*.

In [ ]:
##### 8.3.3 INVESTIGATING THE WIKIPEDIA DATA ##### 8.3.3 INVESTIGATING THE WIKIPEDIA DATA ####################

In [17]:
# converting wiki_movies_raw into a DF to see just how bad it is, data cleaniness wise
wiki_movies_df = pd.DataFrame(wiki_movies_raw)
wiki_movies_df.head()

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990.0,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,Renny Harlin,"[Steve Perry, Joel Silver]","[David Arnott, James Cappe, Daniel Waters]","[David Arnott, James Cappe]","[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990.0,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet",James Foley,"[Ric Kidney, Robert Redlin]","[James Foley, Robert Redlin]",NaN,"[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://en.wikipedia.org/wiki/Air_America_(film),1990.0,https://www.imdb.com/title/tt0099005/,Air America,Roger Spottiswoode,Daniel Melnick,"[John Eskow, Richard Rush]",NaN,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990.0,https://www.imdb.com/title/tt0099012/,Alice,Woody Allen,Robert Greenhut,NaN,NaN,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990.0,https://www.imdb.com/title/tt0099018/,Almost an Angel,John Cornell,John Cornell,NaN,NaN,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# waaay to many columns need to convert DF into list to see all the columns.
# use .columns.tolist() chain to check columns as a list.
wiki_movies_df.columns.tolist()

['url',
 'year',
 'imdb_link',
 'title',
 'Directed by',
 'Produced by',
 'Screenplay by',
 'Story by',
 'Based on',
 'Starring',
 'Narrated by',
 'Music by',
 'Cinematography',
 'Edited by',
 'Productioncompany ',
 'Distributed by',
 'Release date',
 'Running time',
 'Country',
 'Language',
 'Budget',
 'Box office',
 'Written by',
 'Genre',
 'Theme music composer',
 'Country of origin',
 'Original language(s)',
 'Producer(s)',
 'Editor(s)',
 'Production company(s)',
 'Original network',
 'Original release',
 'Productioncompanies ',
 'Executive producer(s)',
 'Production location(s)',
 'Distributor',
 'Picture format',
 'Audio format',
 'Voices of',
 'Followed by',
 'Composer(s)',
 'Created by',
 'Also known as',
 'Opening theme',
 'No. of episodes',
 'Preceded by',
 'Author',
 'Publisher',
 'Publication date',
 'Media type',
 'Pages',
 'ISBN',
 'OCLC',
 'LC Class',
 'Cover artist',
 'Series',
 'Set in',
 'Adaptation by',
 'Suggested by',
 'Biographical data',
 'Born',
 'Died',
 'Resting place',
 'Occupation',
 'Years active',
 'Spouse(s)',
 'Children',
 'Parent(s)',
 'Genres',
 'Instruments',
 'Labels',
 'Website',
 'Traditional',
 'Mandarin',
 'Type',
 'Industry',
 'Fate',
 'Founded',
 'Founder',
 'Headquarters',
 'Parent',
 'Released',
 'Recorded',
 'Venue',
 'Length',
 'Label',
 'Director',
 'Producer',
 'Area',
 'Coordinates',
 'Status',
 'Opening date',
 'Closing date',
 'Replaced',
 'Replaced by',
 'Name',
 'Attraction type',
 'Music',
 'Duration',
 'Simplified Chinese',
 'Traditional Chinese',
 'Hanyu Pinyin',
 'Literal meaning',
 'Transcriptions',
 'Bopomofo',
 'Gwoyeu Romatzyh',
 'Wade–Giles',
 'IPA',
 'Yale Romanization',
 'Jyutping',
 'Hokkien POJ',
 'Animation by',
 'Color process',
 'Engine(s)',
 'Genre(s)',
 'Actor control',
 'Production company',
 'Release(s)',
 'Format(s)',
 'Simplified',
 'Characters',
 'Date premiered',
 'Place premiered',
 'Setting',
 'Original language',
 'Subject',
 'Published',
 'Dewey Decimal',
 'Text',
 'Illustrator',
 'Original title',
 'Published in English',
 'French',
 'Developed by',
 'Ending theme',
 'No. of seasons',
 'Nationality',
 'Portrayed by',
 'Alias',
 'Species',
 'Gender',
 'Family',
 'Alma mater',
 'Camera setup',
 'Novel(s)',
 'Comics',
 'Film(s)',
 'Screen story by',
 'Hangul',
 'Revised Romanization',
 'McCune–Reischauer',
 'Developer(s)',
 'Publisher(s)',
 'Designer(s)',
 'Programmer(s)',
 'Artist(s)',
 'Writer(s)',
 'Engine',
 'Platform(s)',
 'Release',
 'Mode(s)',
 'Original work',
 'Television series',
 'Japanese',
 'Hepburn',
 'Literally',
 'Cantonese',
 'Full name',
 'Height',
 'Seasons',
 'Chinese',
 'Other names',
 'Relatives',
 'Yiddish',
 'Formerly',
 'Key people',
 'Total assets',
 'Owner',
 'Number of employees',
 'Divisions',
 'Subsidiaries',
 'Arabic',
 'Romanized',
 'Predecessor',
 'Founders',
 'Area served',
 'Products',
 'Services',
 'Russian',
 'Hebrew',
 'Revenue',
 'Operating income',
 'Polish']

In [ ]:
############################### using list comphrension to filter data

# modify the JSON data by restricting it to only those entries that have a director and IMDB link.
# [expression FOR element IN source_list]

# to use a filter in list comprehension - [expression FOR element IN source_list IF filter_expression]
# resulting list will only have elemenst where the filter expression is true.

# example if we wanted a list of dogs, and we wanted only those weighing more than 30 pounds.
# [dog FOR dog in dogs if dog["weight"] > 30]

In [19]:
# need to check if either "director" or "directed by" are keys in the current dict. if there is a director 
# listed, we also want to check to see if dict has a IMDB link. which is in the imdb_link column.

# if ("Director" in movie or "Directed by" in movie) and "imdb_link" in movie

wiki_movies = [movie for movie in wiki_movies_raw
              if ("Director" in movie or "Directed by" in movie) 
               and "imdb_link" in movie]

len(wiki_movies)
#output = 7080 movies

7080

In [20]:
# This is why it's easier to load the JSON in first and then convert it to a DataFrame. 
# Instead of trying to identify which columns in our DataFrame don't belong
# we just remove the bad data points, and the bad columns never get imported in.

### MAKE NON DESTRUCTIVE EDITS!!!! don't delete old data sets b/c you might have to go back.

# always create new variables when you move on so you can retrace steps!!!!

In [21]:
# adding the filter for "No. of episodes" into list comphrension since we don't want that obviously.

wiki_movies = [movie for movie in wiki_movies_raw
              if ("Director" in movie or "Directed by" in movie) 
               and "imdb_link" in movie
              and "No. of episodes" not in movie]
len(wiki_movies)
#output = 7076...got another 4 down.

7076

In [22]:
############ 8.3.4 Revisit Functions ############# 8.3.4 ##########

In [23]:
# going to make a function that performs the cleaning process.

# 4 basic parts to a function-
# 1. Name, 2. Parameters, 3. Code Block, 4. Return Value

### Scope.

# Variables created OUTSIDE the function are called **GLOBAL** variables.

# new variables created INSIDE the function are called **LOCAL** variables. (only work inside that specific function)

# The hiearchy of variables is called the SCOPE.

### you can create a local variable with the *same name* as a global variable.
# Inside the fucntion, the local variable takes precendence, but the value
# of the GLOBAL variable will be unchanged. Por exemplo,

x = "global value"

def foo():
    x = "local value"
    print(x)

foo()
print(x)

# output = 

# local value
# global value

# EXPLAINER - outside the function, "x" has the value "global value" Although we define a new function
# after assigning a value to the GLOBAL VARIABLE "x", the "x" INSIDE the function is a **new** variable
# whose SCOPE is local to foo().      Even after calling the foo() fucntion, the GLOBAL VARIABLE "x"
# keeps its original value.

local value
global value

In [24]:
### gotta be careful with sending MUTABLE objects into functions, because they'll be changed outside the function.

# example

my_list = [1,2,3]
def append_four(x):
    x.append(4)
append_four(my_list)
print(my_list)

# output = [1, 2, 3, 4]

# it changed my_list.  WE GOTTA MAKE A COPY.

# for lists, we make a copy with the "list" funciton
new_list = list(old_list)

# for dicts, we make a copy with the "dict" function
new_dict = dict(old_dict)

[1, 2, 3, 4]

NameError: name 'old_list' is not defined

In [25]:
###### LAMBDA FUNCTIONS ###### ###### LAMBDA FUNCTIONS ############ LAMBDA FUNCTIONS ############ LAMBDA FUNCTIONS ######

In [61]:
# Lambda functions are written in one line and auto return a value without using the RETURN keyword.
# they have no name and are AKA "anonymous functions"
# lambda functions are a way to quickly create a concise function to send as a parameter to another function.

#basic syntax for lambda function : 

lambda arguments : expression

In [62]:
# this function will take in an argument and return the expression.
# following example is named, but that's only so we can see how they work, normally NOT named
# function that squares a value-

lambda x: x * x

# Here "x" is the ARGUMENT and "x * x" is the EXPRESSION

square = lambda x: x * x
square(5)

#output is 25

25

In [ ]:
###### 8.3.5 ####### Create a funtion to clean the data, P1 ###### 8.3.5 ######## 8.3.5

In [ ]:
# Write a simple function to make a copy of the movie and return it.  
# call the function "clean_movie" and have it take "movie" as a parameter

def clean_movie(movie):

    
# because the movies are dicts and we want to make NONDESTRUCTIVE edits, make a copy of incoming movie.
# to make a copy of the "movie" use the dict() constructor.

In [26]:
# CONSTRUCTORS are special functions that intiliaze new objects. They can take parameters and initialize a new
# objects using those parameters.

# when we pass "movie" as a parameter to the dict() constructor, it reserves a new space in memory and copies all
# of the info in "movie" to the new space.

# could start our function off like this:
#        def clean_movie(movie):
#              movie_copy = dict(movie)

# HOWEVER, THIS IS BETTER.
# inside of the function, we can create a new local variable called "movie" and assign it the new copy
# of the PARAMETER movie.

def clean_movie(movie):
    movie = dict(movie) # create a non-destructive copy
    
# this way, inside the CLEAN_MOVIE function, "movie" will refer to the LOCAL copy.  Any changes we make 
# inside CLEAN_MOVIE() will now only affect the copy, so we have the original, untouched "movie" if we make a mistake.

In [27]:
 # to finish out skeleton of CLEAN_MOVIE fucntion, return the movie variable.
def clean_movie(movie):
    movie = dict(movie) # create a non-dest. copy
    return movie

In [28]:
# languages in the movie list. Arabic. see which have a value for it.

wiki_movies_df[wiki_movies_df["Arabic"].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
7060,https://en.wikipedia.org/wiki/The_Insult_(film),2018.0,https://www.imdb.com/title/tt7048622/,The Insult,Ziad Doueiri,"[Rachid Bouchareb, Jean Bréhat, Julie Gayet, A...",NaN,NaN,NaN,"[Adel Karam, Kamel El Basha]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7293,https://en.wikipedia.org/wiki/Capernaum_(film),2018.0,https://www.imdb.com/title/tt8267604/,Capernaum,Nadine Labaki,"[Michel Merkt, Khaled Mouzanar]","[Nadine Labaki, Jihad Hojaily, Michelle Keserw...","[Georges Khabbaz, Nadine Labaki, Michelle Kese...",NaN,"[Zain Al Rafeea, Yordanos Shiferaw, Boluwatife...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
# can directly visit the URL by adding that to the chain.
wiki_movies_df[wiki_movies_df["Arabic"].notnull()]["url"]

# 7060    https://en.wikipedia.org/wiki/The_Insult_(film)
# 7293     https://en.wikipedia.org/wiki/Capernaum_(film)

7060    https://en.wikipedia.org/wiki/The_Insult_(film)
7293     https://en.wikipedia.org/wiki/Capernaum_(film)
Name: url, dtype: object

In [31]:
# the different langauges column in the wiki_movies_df are for alternate titles of the movie. 
# combine all of them into ONE dictionary that has all alt. titles.

# SKILL CHALLENGE
# go through each of the columns and determine which columns hold alt. titles.
sorted(wiki_movies_df.columns.tolist())

['Actor control',
 'Adaptation by',
 'Alias',
 'Alma mater',
 'Also known as',
 'Animation by',
 'Arabic',
 'Area',
 'Area served',
 'Artist(s)',
 'Attraction type',
 'Audio format',
 'Author',
 'Based on',
 'Biographical data',
 'Bopomofo',
 'Born',
 'Box office',
 'Budget',
 'Camera setup',
 'Cantonese',
 'Characters',
 'Children',
 'Chinese',
 'Cinematography',
 'Closing date',
 'Color process',
 'Comics',
 'Composer(s)',
 'Coordinates',
 'Country',
 'Country of origin',
 'Cover artist',
 'Created by',
 'Date premiered',
 'Designer(s)',
 'Developed by',
 'Developer(s)',
 'Dewey Decimal',
 'Died',
 'Directed by',
 'Director',
 'Distributed by',
 'Distributor',
 'Divisions',
 'Duration',
 'Edited by',
 'Editor(s)',
 'Ending theme',
 'Engine',
 'Engine(s)',
 'Executive producer(s)',
 'Family',
 'Fate',
 'Film(s)',
 'Followed by',
 'Format(s)',
 'Formerly',
 'Founded',
 'Founder',
 'Founders',
 'French',
 'Full name',
 'Gender',
 'Genre',
 'Genre(s)',
 'Genres',
 'Gwoyeu Romatzyh',
 'Hangul',
 'Hanyu Pinyin',
 'Headquarters',
 'Hebrew',
 'Height',
 'Hepburn',
 'Hokkien POJ',
 'IPA',
 'ISBN',
 'Illustrator',
 'Industry',
 'Instruments',
 'Japanese',
 'Jyutping',
 'Key people',
 'LC Class',
 'Label',
 'Labels',
 'Language',
 'Length',
 'Literal meaning',
 'Literally',
 'Mandarin',
 'McCune–Reischauer',
 'Media type',
 'Mode(s)',
 'Music',
 'Music by',
 'Name',
 'Narrated by',
 'Nationality',
 'No. of episodes',
 'No. of seasons',
 'Novel(s)',
 'Number of employees',
 'OCLC',
 'Occupation',
 'Opening date',
 'Opening theme',
 'Operating income',
 'Original language',
 'Original language(s)',
 'Original network',
 'Original release',
 'Original title',
 'Original work',
 'Other names',
 'Owner',
 'Pages',
 'Parent',
 'Parent(s)',
 'Picture format',
 'Place premiered',
 'Platform(s)',
 'Polish',
 'Portrayed by',
 'Preceded by',
 'Predecessor',
 'Produced by',
 'Producer',
 'Producer(s)',
 'Production company',
 'Production company(s)',
 'Production location(s)',
 'Productioncompanies ',
 'Productioncompany ',
 'Products',
 'Programmer(s)',
 'Publication date',
 'Published',
 'Published in English',
 'Publisher',
 'Publisher(s)',
 'Recorded',
 'Relatives',
 'Release',
 'Release date',
 'Release(s)',
 'Released',
 'Replaced',
 'Replaced by',
 'Resting place',
 'Revenue',
 'Revised Romanization',
 'Romanized',
 'Running time',
 'Russian',
 'Screen story by',
 'Screenplay by',
 'Seasons',
 'Series',
 'Services',
 'Set in',
 'Setting',
 'Simplified',
 'Simplified Chinese',
 'Species',
 'Spouse(s)',
 'Starring',
 'Status',
 'Story by',
 'Subject',
 'Subsidiaries',
 'Suggested by',
 'Television series',
 'Text',
 'Theme music composer',
 'Total assets',
 'Traditional',
 'Traditional Chinese',
 'Transcriptions',
 'Type',
 'Venue',
 'Voices of',
 'Wade–Giles',
 'Website',
 'Writer(s)',
 'Written by',
 'Yale Romanization',
 'Years active',
 'Yiddish',
 'imdb_link',
 'title',
 'url',
 'year']

In [32]:
wiki_movies_df["Alma mater"].value_counts()

Loyola Marymount University    1
Rutgers University             1
Name: Alma mater, dtype: int64

In [74]:
wiki_movies_df["Based on"].count()

2199

In [75]:
wiki_movies_df["Director"].value_counts()

Mark "Aldo" Miceli    1
Rocky Schenck         1
Name: Director, dtype: int64

In [33]:
wiki_movies_df["Language"].value_counts()

English                                       6361
[English, Spanish]                              77
[English, French]                               35
[English, Japanese]                             28
[English, Russian]                              23
                                              ...
[English, Navajo]                                1
[English, French, Mandarin Chinese, Hindi]       1
[English, ,, Filipino]                           1
[Korean, English]                                1
[English, Jamaican Patois, French]               1
Name: Language, Length: 224, dtype: int64

In [72]:
wiki_movies_df["Based on"].value_counts()

[Star Trek, by, Gene Roddenberry]                                                   8
[Teenage Mutant Ninja Turtles, by, Kevin Eastman, Peter Laird]                      6
[Transformers, by, Hasbro]                                                          6
[Mission: Impossible, by, Bruce Geller]                                             6
[Characters, by, Gary Scott Thompson]                                               5
                                                                                   ..
[Hairspray, by, John Waters, Hairspray, by, Mark O'Donnell, Thomas Meehan]          1
[Beautiful Creatures, by, Kami Garcia, Margaret Stohl]                              1
[Nightmare of Ecstasy: The Life and Art of Edward D. Wood Jr., by, Rudolph Grey]    1
[Walking Across Egypt, by, Clyde Edgerton]                                          1
[Angry Birds, by, Rovio Entertainment]                                              1
Name: Based on, Length: 1986, dtype: int64

In [ ]:
# Here is a complete list of columns that hold alternate title data: Also known as, Arabic, Cantonese, 
# Chinese, French, Hangul, Hebrew, 
# Hepburn, Japanese, Literally,  Mandarin, McCune–Reischauer, Original title, Polish,  Revised Romanization, 
# Romanized, Russian, Simplified, Traditional, Yiddish

In [ ]:
##### HANDLE THE ALTERNATIVE TITLES ##### 8.3.5 still ####
# Logic we need to implement follows:

# 1. make an empty DICT to hold all the alternative titles.

# 2. Loop through a list of all alternative title keys:
#     check if the current key exists in the movie object
    
#     if so, remove the key-value pair and add to the alternative titles dict.
    
# 3. after looping through every key, add the alternative titles DICT to the movie object.

In [34]:
# STEP 1. Make an empty dict to hold all the alternative titles

def clean_movie(movie):
    movie = dict(movie) # create a non-dest. copy
    alt_titles = {}
    return movie

In [36]:
# STEP 2. Loop throuhg a list of all alternative title keys.

def clean_movie(movie):
    movie = dict(movie)
    alt_titles = {}
    for key in ["Also known as", "Arabic", "Cantonese", "Chinese", "French", 
                "Hangul", "Hebrew", "Hepburn", "Japanese", "Literally", "Mandarin",
                "McCune–Reischauer", "Original title", "Polish",  "Revised Romanization", 
                "Romanized", "Russian", "Simplified", "Traditional", "Yiddish"]:
        return movie

In [42]:
# STEP 2a. Check to see if current key exists in the movie object.

def clean_movie(movie):
    movie = dict(movie)
    alt_titles = {}
    for key in ["Also known as", "Arabic", "Cantonese", "Chinese", "French", 
                "Hangul", "Hebrew", "Hepburn", "Japanese", "Literally", "Mandarin",
                "McCune–Reischauer", "Original title", "Polish",  "Revised Romanization", 
                "Romanized", "Russian", "Simplified", "Traditional", "Yiddish"]:
        if key in movie:
            return movie

In [43]:
# STEP 2b. If so, remove key-value pair and add to the alt. titles dict.
def clean_movie(movie):
    movie = dict(movie)
    alt_titles = {}
    for key in ["Also known as", "Arabic", "Cantonese", "Chinese", "French", 
                "Hangul", "Hebrew", "Hepburn", "Japanese", "Literally", "Mandarin",
                "McCune–Reischauer", "Original title", "Polish",  "Revised Romanization", 
                "Romanized", "Russian", "Simplified", "Traditional", "Yiddish"]:
        if key in movie:
            alt_titles[key] = movies[key]
            movie.pop(key)
        
    return movie

In [44]:
# STEP 3. After looping through every key, add the alt titles dict to the movies object.

def clean_movie(movie):
    movie = dict(movie)
    alt_titles = {}
    for key in ["Also known as", "Arabic", "Cantonese", "Chinese", "French", 
                "Hangul", "Hebrew", "Hepburn", "Japanese", "Literally", "Mandarin",
                "McCune–Reischauer", "Original title", "Polish",  "Revised Romanization", 
                "Romanized", "Russian", "Simplified", "Traditional", "Yiddish"]:
        if key in movie:
            alt_titles[key] = movie[key]
            movie.pop(key)
    if len(alt_titles) > 0:
        movie["alt_titles"] = alt_titles
        
    return movie

# can make a list of cleaned movies with a list comphrension:
clean_movies = [clean_movie(movie) for movie in wiki_movies]

# Set "wiki_movies_df" to be the DF created from "clean_movies" and print out list of columns

wiki_movies_df = pd.DataFrame(clean_movies)
sorted(wiki_movies_df.columns.tolist())

['Adaptation by',
 'Animation by',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Country of origin',
 'Created by',
 'Directed by',
 'Director',
 'Distributed by',
 'Distributor',
 'Edited by',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'Genre',
 'Label',
 'Language',
 'Length',
 'Music by',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Original release',
 'Picture format',
 'Preceded by',
 'Produced by',
 'Producer',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Productioncompanies ',
 'Productioncompany ',
 'Recorded',
 'Release date',
 'Released',
 'Running time',
 'Screen story by',
 'Screenplay by',
 'Starring',
 'Story by',
 'Suggested by',
 'Theme music composer',
 'Venue',
 'Voices of',
 'Written by',
 'alt_titles',
 'imdb_link',
 'title',
 'url',
 'year']

In [ ]:
# 8.3.6 ##### # 8.3.6 ##### Create function to clean data P2 # 8.3.6 ###### 8.3.6 ###### 8.3.6 ###### 8.3.6 ###### 8.3.6 #####

In [ ]:
# have a bunch of columns that contain similiar data but under different names.
# i.e. "directed by" and director"

# Can use the POP() method to change the name of a dictionary key, because POP() returns the value
# from the removed key-value pair. We have to check if the key exists in a given movie record
# so we'll make a small function inside CLEAN_MOVIE()

In [ ]:
# def change_column_name(old_name, new_name):
#     if old_name in movie:
#         movie[new_name] = movie.pop(old_name)

In [ ]:
# To change every instance where the key is "directed by" to the
# NEW KEY- "Director" 
def change_column_name("Directed by", "Director"): #(old key, new key)

In [ ]:
# List of all the keys we're combining into new_name(s)
   change_column_name('Adaptation by', 'Writer(s)')
    change_column_name('Country of origin', 'Country')
    change_column_name('Directed by', 'Director')
    change_column_name('Distributed by', 'Distributor')
    change_column_name('Edited by', 'Editor(s)')
    change_column_name('Length', 'Running time')
    change_column_name('Original release', 'Release date')
    change_column_name('Music by', 'Composer(s)')
    change_column_name('Produced by', 'Producer(s)')
    change_column_name('Producer', 'Producer(s)')
    change_column_name('Productioncompanies ', 'Production company(s)')
    change_column_name('Productioncompany ', 'Production company(s)')
    change_column_name('Released', 'Release Date')
    change_column_name('Release Date', 'Release date')
    change_column_name('Screen story by', 'Writer(s)')
    change_column_name('Screenplay by', 'Writer(s)')
    change_column_name('Story by', 'Writer(s)')
    change_column_name('Theme music composer', 'Composer(s)')
    change_column_name('Written by', 'Writer(s)')

In [45]:
# Add the change_column_name items to the CLEAN_MOVIE() function
def clean_movie(movie):
    movie = dict(movie)
    alt_titles = {}
    for key in ["Also known as", "Arabic", "Cantonese", "Chinese", "French", 
                "Hangul", "Hebrew", "Hepburn", "Japanese", "Literally", "Mandarin",
                "McCune–Reischauer", "Original title", "Polish",  "Revised Romanization", 
                "Romanized", "Russian", "Simplified", "Traditional", "Yiddish"]:
        if key in movie:
            alt_titles[key] = movie[key]
            movie.pop(key)
    if len(alt_titles) > 0:
        movie["alt_titles"] = alt_titles
    
    # merge column names
    def change_column_name(old_name, new_name):
        if old_name in movie:
            movie[new_name] = movie.pop(old_name)
    change_column_name('Adaptation by', 'Writer(s)')
    change_column_name('Country of origin', 'Country')
    change_column_name('Directed by', 'Director')
    change_column_name('Distributed by', 'Distributor')
    change_column_name('Edited by', 'Editor(s)')
    change_column_name('Length', 'Running time')
    change_column_name('Original release', 'Release date')
    change_column_name('Music by', 'Composer(s)')
    change_column_name('Produced by', 'Producer(s)')
    change_column_name('Producer', 'Producer(s)')
    change_column_name('Productioncompanies ', 'Production company(s)')
    change_column_name('Productioncompany ', 'Production company(s)')
    change_column_name('Released', 'Release Date')
    change_column_name('Release Date', 'Release date')
    change_column_name('Screen story by', 'Writer(s)')
    change_column_name('Screenplay by', 'Writer(s)')
    change_column_name('Story by', 'Writer(s)')
    change_column_name('Theme music composer', 'Composer(s)')
    change_column_name('Written by', 'Writer(s)')
    
    return movie

# now we can rerun our list comprehension to clean WIKI_MOVIES and recreate WIKI_MOVIES_DF

clean_movies = [clean_movie(movie) for movie in wiki_movies]
wiki_movies_df = pd.DataFrame(clean_movies)

# let's check out how that looks sorted.

sorted(wiki_movies_df.columns.tolist())

['Animation by',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Created by',
 'Director',
 'Distributor',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'Genre',
 'Label',
 'Language',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Picture format',
 'Preceded by',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Recorded',
 'Release date',
 'Running time',
 'Starring',
 'Suggested by',
 'Venue',
 'Voices of',
 'Writer(s)',
 'alt_titles',
 'imdb_link',
 'title',
 'url',
 'year']

In [ ]:
###### 8.3.7 ##### REMOVE DUPLICATE ROWS ##### 8.3.7 ###### 8.3.7 #######

In [ ]:
# REGULAR EXPRESSIONS #

# Regular expressions, or regex, are strings of characters that define a search pattern.
# An example from non-coding would be "MM/DD/YYYY" - it's a pattern for entering dates. Or (###)-###-#### for U.S. phone #s
# Regular expressions are a formal way of defining those kinds of patterns so that the code we're writting can find them.

# USED TO SEARCH FOR PATTERNS IN TEXT

In [46]:
wiki_movies_df["imdb_link"]

# output example - https://www.imdb.com/title/tt0098987/    **the tt0098987 is the IMDB id!

0       https://www.imdb.com/title/tt0098987/
1       https://www.imdb.com/title/tt0098994/
2       https://www.imdb.com/title/tt0099005/
3       https://www.imdb.com/title/tt0099012/
4       https://www.imdb.com/title/tt0099018/
                        ...
7071    https://www.imdb.com/title/tt1255919/
7072    https://www.imdb.com/title/tt6266538/
7073    https://www.imdb.com/title/tt4669788/
7074    https://www.imdb.com/title/tt7137380/
7075    https://www.imdb.com/title/tt9495224/
Name: imdb_link, Length: 7076, dtype: object

In [ ]:
# Going to use the STR property.  With str.extract() which takes in a REGULAR EXPRESSION pattern.
# the IMDB id starts with "tt" and has 7 digits following that.

# "(tt\d{7})"

# Breakdown - 
# the parantheses marks say to look for ONE group of text.

# the "tt" in the string says to match for two lowercase Ts.

# the \d says to match a numerical digit.

# the {7} | the {7} says to match thing (in this case, numberical digits) EXACTLY 7 times.

#### SINCE regular expressions use \ (backslashes) which python also uses for special characters,
# want to tell python to treat our REGULAR EXPRESSION characters as a *raw* string of text.
# to do so, put an **r** before the quotes.  

#  ^ need to do that every time we create a regular expression string.

In [47]:
# code to extract IMDb ID 
wiki_movies_df["imdb_link"] = wiki_movies_df["imdb_link"].str.extract(r"(tt\d{7})")

In [ ]:
# Now we can drop any duplicates of IMDb IDs using the drop_duplicates() method.
# to specify that we only want to consider the IMDb ID, use the *subset* argument, -- only considering the "imdb_id" to
# determine if it's a duplicate -- 
# set *inplace* equal to True.

# also want to see the new number of rows and how many rows were dropped.

In [48]:
wiki_movies_df["imdb_id"] = wiki_movies_df["imdb_link"].str.extract(r"(tt\d{7})")
print(len(wiki_movies_df))

# output - 7076 (movies)

7076

In [49]:
wiki_movies_df.drop_duplicates(subset = "imdb_id", inplace = True) # "imdb_id" was defined above as new column in df
print(len(wiki_movies_df))

#output - 7033 (movies)

7033

In [50]:
wiki_movies_df.head()

,url,year,imdb_link,title,Based on,Starring,Narrated by,Cinematography,Release date,Running time,...,Created by,Preceded by,Suggested by,alt_titles,Recorded,Venue,Label,Animation by,Color process,imdb_id
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,tt0098987,The Adventures of Ford Fairlane,"[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...","Andrew ""Dice"" Clay",Oliver Wood,"[July 11, 1990, (, 1990-07-11, )]",102 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0098987
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,tt0098994,"After Dark, My Sweet","[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",NaN,Mark Plummer,"[May 17, 1990, (, 1990-05-17, ), (Cannes Film ...",114 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0098994
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,tt0099005,Air America,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",NaN,Roger Deakins,"[August 10, 1990, (, 1990-08-10, )]",113 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0099005
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,tt0099012,Alice,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",NaN,Carlo Di Palma,"[December 25, 1990, (, 1990-12-25, )]",106 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0099012
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,tt0099018,Almost an Angel,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",NaN,Russell Boyd,"December 19, 1990",95 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0099018

In [51]:
# using list comprehension to get a count null values for EACH column

[[column, wiki_movies_df[column].isnull().sum()] for column in wiki_movies_df.columns]

[['url', 0],
 ['year', 0],
 ['imdb_link', 0],
 ['title', 1],
 ['Based on', 4852],
 ['Starring', 184],
 ['Narrated by', 6752],
 ['Cinematography', 691],
 ['Release date', 32],
 ['Running time', 139],
 ['Country', 236],
 ['Language', 244],
 ['Budget', 2295],
 ['Box office', 1548],
 ['Director', 0],
 ['Distributor', 357],
 ['Editor(s)', 548],
 ['Composer(s)', 518],
 ['Producer(s)', 202],
 ['Production company(s)', 1678],
 ['Writer(s)', 199],
 ['Genre', 6923],
 ['Original language(s)', 6875],
 ['Original network', 6908],
 ['Executive producer(s)', 6936],
 ['Production location(s)', 6986],
 ['Picture format', 6969],
 ['Audio format', 6972],
 ['Voices of', 7031],
 ['Followed by', 7024],
 ['Created by', 7023],
 ['Preceded by', 7023],
 ['Suggested by', 7032],
 ['alt_titles', 7012],
 ['Recorded', 7031],
 ['Venue', 7032],
 ['Label', 7031],
 ['Animation by', 7031],
 ['Color process', 7032],
 ['imdb_id', 0]]

In [52]:
# Bunch of columns with 6k plus null values... make a list of columns that have LESS THAN 90% null values
[column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9]

['url',
 'year',
 'imdb_link',
 'title',
 'Based on',
 'Starring',
 'Cinematography',
 'Release date',
 'Running time',
 'Country',
 'Language',
 'Budget',
 'Box office',
 'Director',
 'Distributor',
 'Editor(s)',
 'Composer(s)',
 'Producer(s)',
 'Production company(s)',
 'Writer(s)',
 'imdb_id']

In [94]:
# this gives us the list of columns to keep... which we can select from in our PD df

wiki_columns_to_keep = [column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9]

wiki_movies_df = wiki_movies_df[wiki_columns_to_keep]

wiki_movies_df.head()

,url,year,imdb_link,title,Based on,Starring,Cinematography,Release date,Running time,Country,...,Budget,Box office,Director,Distributor,Editor(s),Composer(s),Producer(s),Production company(s),Writer(s),imdb_id
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,tt0098987,The Adventures of Ford Fairlane,"[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",Oliver Wood,"[July 11, 1990, (, 1990-07-11, )]",102 minutes,United States,...,$20 million,$21.4 million,Renny Harlin,20th Century Fox,Michael Tronick,"[Cliff Eidelman, Yello]","[Steve Perry, Joel Silver]",Silver Pictures,"[David Arnott, James Cappe]",tt0098987
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,tt0098994,"After Dark, My Sweet","[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",Mark Plummer,"[May 17, 1990, (, 1990-05-17, ), (Cannes Film ...",114 minutes,United States,...,$6 million,$2.7 million,James Foley,Avenue Pictures,Howard E. Smith,Maurice Jarre,"[Ric Kidney, Robert Redlin]",Avenue Pictures,"[James Foley, Robert Redlin]",tt0098994
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,tt0099005,Air America,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",Roger Deakins,"[August 10, 1990, (, 1990-08-10, )]",113 minutes,United States,...,$35 million,"$57,718,089",Roger Spottiswoode,TriStar Pictures,"[John Bloom, Lois Freeman-Fox]",Charles Gross,Daniel Melnick,"[Carolco Pictures, IndieProd Company]","[John Eskow, Richard Rush]",tt0099005
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,tt0099012,Alice,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",Carlo Di Palma,"[December 25, 1990, (, 1990-12-25, )]",106 minutes,United States,...,$12 million,"$7,331,647",Woody Allen,Orion Pictures,Susan E. Morse,NaN,Robert Greenhut,NaN,Woody Allen,tt0099012
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,tt0099018,Almost an Angel,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",Russell Boyd,"December 19, 1990",95 minutes,US,...,$25 million,"$6,939,946 (USA)",John Cornell,Paramount Pictures,David Stiven,Maurice Jarre,John Cornell,NaN,Paul Hogan,tt0099018

In [ ]:
##### 8.3.8 ###### Make a plan to convert and parse the data #### 8.3.8 ##### 8.3.8 ######

In [95]:
# indentify which columns need to be converted.

wiki_movies_df.dtypes

url                      object
year                      int64
imdb_link                object
title                    object
Based on                 object
Starring                 object
Cinematography           object
Release date             object
Running time             object
Country                  object
Language                 object
Budget                   object
Box office               object
Director                 object
Distributor              object
Editor(s)                object
Composer(s)              object
Producer(s)              object
Production company(s)    object
Writer(s)                object
imdb_id                  object
dtype: object

In [ ]:
# box office, budget, running time SHOULD be numeric.
# release date SHOULD be a date object.

In [53]:
# looking at box office first, drop the NAs.
box_office = wiki_movies_df["Box office"].dropna()

# make a habit out of checking how many data points you drop/alter when you do those functions.

# think about if the number that have been altered makes sense.

In [ ]:
# using REGULAR EXPRESSIONS to parse "box office"

# Regular expressions only work on STRINGS!! so we need to make sure all box office data is entered as a string.

# using the apply( ) method, can see which values are NOT strings. 

# make a---- is_not_a_string() function

In [54]:
def is_not_a_string(x):
    return type(x) != str

In [55]:
# add box_office[box_office.map()] to the function.

box_office[box_office.map(is_not_a_string)]

34                           [US$, 4,212,828]
54      [$6,698,361 (, United States, ), [2]]
74                    [$6,488,144, (US), [1]]
126                [US$1,531,489, (domestic)]
130                          [US$, 4,803,039]
                        ...
6980               [$99.6, million, [4], [5]]
6994                   [$365.6, million, [1]]
6995                         [$53.8, million]
7015                     [$435, million, [7]]
7048                   [$529.3, million, [4]]
Name: Box office, Length: 135, dtype: object

In [56]:
# instead of doing that everytime, can use lambda functions and insert them right inside the map( ) call.

# syntax for lambda: lambda arguments: expression

# lambada function version of is_not_a_string() is:

lambda x: type(x) != str

In [57]:
# can updated our map ( ) call to use the lambda function directly instead of is_not_a_string()

# type(x) != str is saying that if the datatype of the value in the box office column ISNT a string, call it.

box_office[box_office.map(lambda x: type(x) != str)]

34                           [US$, 4,212,828]
54      [$6,698,361 (, United States, ), [2]]
74                    [$6,488,144, (US), [1]]
126                [US$1,531,489, (domestic)]
130                          [US$, 4,803,039]
                        ...
6980               [$99.6, million, [4], [5]]
6994                   [$365.6, million, [1]]
6995                         [$53.8, million]
7015                     [$435, million, [7]]
7048                   [$529.3, million, [4]]
Name: Box office, Length: 135, dtype: object

In [102]:
# join () string method 
# concatenates list items into one string.
# Need to make a separator string and then call the join() method on it.

################## example ################# 

some_list = ["one", "two", "three"]
"Mississippi".join(some_list)

# output = 'oneMississippitwoMississippithree'

'oneMississippitwoMississippithree'

In [58]:
# Use a simple "space" as our joining character and apply the join()
# function only when our data points are lists.

box_office = box_office.apply(lambda x: " ".join(x) if type(x) == list else x)
box_office

0          $21.4 million
1           $2.7 million
2            $57,718,089
3             $7,331,647
4       $6,939,946 (USA)
              ...
7070       $19.4 million
7071       $41.9 million
7072       $76.1 million
7073       $38.4 million
7074        $5.5 million
Name: Box office, Length: 5485, dtype: object

In [105]:
# import regular expressions
import re

In [ ]:
################### 8.3.9 ########## WRITE REGULAR EXPRESSIONS ######## 8.3.9 ############# 8.3.9 ####################

In [ ]:
# Regular expressions are just strings of characters that are used as a search pattern.


# They are used to test if strings are in a specific format
# or contain a substring in a specific format
# to extract pertinent information from strings while discarding unnecessary info
# to perform complicated replacements of substrings.

In [ ]:
# Literal Characters (regular expressions)

# the simplest character class.  a regular expression comprised of literal characters will 
# match any string that contains the expression as a substring.

# example, if you made a reg expression of the string "cat" and used it search for any matches in another string-
# "The tomcat was placated with the catch of the day" 
# it would match 3 times. tom(cat) was pla(cat)ed with the (cat)ch of the day

In [107]:
# Character types : \d, \D, \w, \W, \s, \S

# \d - will  match any digit from 0 to 9.

# \D - will match any non-digit character.

# \w - matches a word character (a letter, digit, or underscore)

# \W - matches any non-word character (anything other than a letter, digit, or underscore,
#                                     such as SPACES and puncuation)

# \s - will match any whitespace character (including SPACES, tabs, and newlines)

# \S - will match any non-whitespace characters.

In [108]:
# Character Sets: []

# if you need to be more specific than digits, alphanumeric characters or white space characters,
# use square brackets to define a character set.

# example

# "[ceh]at" would match the following: "cat", "eat", "hat", "that" but NOT "rat"

############# can include multiple ranges as well. ############## 

# "[a-zA-Z]" matches any lowercase or uppercase letter
# "[a-zA-Z0-9]" matches any alphanumeric character.

############# can also have much smaller ranges as well

# "[A-E]" will match "A", "B", "C", "D", "E"
# "[1-3]" will match "1", "2", "3"

##### ALSO, inside of a character set, you can specify a character that you DO NOT want to 
##### include  by prefacing it was a caret: ^

In [ ]:
# Match (almost) anything: . (period, or dot)

# the *period*, or *dot* (.) is a WILDCARD in regular expressions
# meaning it'll match any single character whether it's a digit, a letter, whitespace, or puncuation.
# only thing it WONT match is a line break.

In [ ]:
# Escaping: \ 

# the dot and square brackets are examples of METACHARACTERS in regular expressions.
# They're like superheroes in regular expressions b/c they have power to "match anything" or "create a character set"

# but let's say you need a METACHARACTER to act like an ordinary literal character.
# Example- if you use regular expression "ca." the DOT (as a metacharacter) will match any character,
# so "cat", "car", "cab", "cart" "ca!" "ca?" "ca." would all be matches.

# But if you wanted to SPECIFICALLY search for only "ca." with an actual period,
# you'd need to use ** \ ** (BACKSLASH) .  
# BACKSLASH tells the parser to treat the upcoming METACHARACTER like a LITERAL character.
# so using "ca\." will ONLY match "ca.", "cat", "car", "cab" 

# using the BACKSLASH in a regular expression like this is called the ESCAPE CHARACTER.
# meaning that the next character gets to ESCAPE it's duties as a special character in the regular expression.

In [ ]:
# curly braces - regular expressions {}

# Use CURLY BRACES when you want to search for a character that shows up an exact number of times.
# When we extracted the IMDb IDs, wanted IDs that had EXACTLY 7 digits, so "\d{7}"

# Can also put 2 numbers in CURLY BRACKETS and that would match for any number of digits within that range.
# example:

# "ca{3}t" would match for "caaat" but NOT "cat" or "caat"
# "ca{3, 5}t" would match "caaat", "caaaat", "caaaaat" but NOT "cat" or "caaaaaaat"

In [ ]:
# ALTERATION | in regular expressions

# alteration character - ( | ), or pipe, functions pretty much as a logical OR.
# example:

# if you wanted to match "man" or "bear" or "pig" make a string "man|bear|pig"

In [ ]:
# STRING BOUNDARIES: \^ and \$

# if you need to make sure that the string you're searching for only matches on either the BEGINNING or END of the string
# you can use the caret (\^) to represent the BEGINNING 
# and the dollar sign (\$) to represent the END of the string.

# example:

# "\^cat" would match "cat" and "CATatonic" but NOT "concatenate"

# "cat\$" would match "cat" and "tomCAT" but NOT "catatonic"

In [ ]:
# Capture Groups: () REGULAR EXPRESSIONS

# Grouping in regular expressions serves two purposes.  

# first, groups can be used to add strucutre to a search pattern.
# example:

# "1,000", "1,000,000" and "1,000,000,000" as STRINGS all have similiar structure.
# there is comma followed by 3 zeros that repeats as a group. You can match all of those with one regular expression- 
# using parentheses to create a **CAPTURE GROUP**.
### the regular expression that matches all three strings would be: "1(,000)+"


# Second purpose for grouping is hinted in the name "capture group"
# CAPTURE GROUPS are how regular expressions define what information should be extracted.
# For example, when we needed to extract IMDb IDs from the links, put the entire expression inside brackets ().
# This can be helpful when you need to make sure a long string matches a certain format, but you only need a substring inside it
# EXAMPLE

# "\d{3}-\d{3}-\d{4}" would match any phone number in the form "333-333-4444" 
# but if you wanted to extract only the digits, you would use: "(\d{3})-(\d{3})-(\d{4})" and ONLY the digits would be captured.
# Specifically, the digits of the phone number would be captured into three *GROUPS*- area code, prefix, and line number.

In [1]:
# NON CAPTURE GROUPS: (?:)

# Can modify the behavior of a group by including a question mark (?) after the opening parenthesis.
# the first modification is a NON-CAPTURING GROUP, which uses a colon (:) after the question mark (?:).
# this specifies that we only to use the grouping structure, and we do **NOT** need to capture the information.

# Using non-capture groups is important when using REGULAR EXPRESSIONS for Matching AND REPLACING.
# EXAMPLE:

# We're looking at phone numbers of the form "333-333-4444" and we want to change the prefix to "555". 
# We still need to have groups in our regular expression for the area code and four-digit line number,
# BUT WE DON'T WANT TO CAPTURE THEM- only want to CAPTURE the prefix.

# We'd use the regular expression: "(?:\d{3})-(\d{3})-(?:\d{4})"
# This will match the numbers of the form "123-456-7890" but it will ONLY CAPTURE the MIDDLE group (the prefix)

# example: "212-012-9876" matches the regular expression "(?:\d{3})-(\d{3})-(?:\d{4})" but ONLY "012" will be captured.
# So, if we used this reg expression to replace the captured text with "555" 
# it would turn "212-012-9876" INTO "212-*555*-9876"

# importantly, "012-3456" WOULDNT MATCH AT ALL, b/c there's no area code. Even though the area code is 
# in a NON-CAPTURING GROUP, the regular expression still needs to see it before it make a match.

In [ ]:
# NEGATIVE LOOKAHEAD GROUPS (a form of non-capturing groups)

# Negative lookahead groups: look ahead in the text and make sure a string doesn't exist AFTER the match.
# EXAMPLE:

# imagine we have text that contains the phone numbers in the form "333-333-4444" but the text
# also contains ID numbers in the form "333-333-55555". 
# the regular expression we've been using: "(\d{3})-(\d{3})-(\d{4})" will see the FIRST 10 digits
# of the ID number and recognize a match (incorrectly b/c we only want the phone numbers to match, NOT ID numbers)
# and return "333-333-5555" as if it were a phone number.

# So, what we need is a REGULAR EXPRESSION that MATCHES the first 10 numbers BUT ALSO checks that there
# isn't another digit after the phone number (because if there was, then it's actually an ID number).
# We need a GROUP that looks ahead of the rest of the regular expression, and reports back
# "negative" if there's some text we don't want to see.

# What is described above is a NEGATIVE LOOKAHEAD GROUP. 

# Negative lookahead groups start with a question mark and an exclamation mark.  So, to make sure there no extra
# digits in our example, a negative lookahead group would be:    "(?!\d)"
#
# Adding the negative lookahead group to our regular expression:
#       "(\d{3})-(\d{3})-(\d{4})(?!\d)"

# "333-333-4444" will match. (yay)
# "333-333-55555" will NOT match (yay)

In [2]:
### CHEAT SHEET CHART FOR REGULAR EXPRESSIONS

# LITERAL CHARACTERS | Directly mathces characters | "cat" | "cat" (match) "dog" (NO match)

# \d                 | Matches a digit from 0 to 9 | "\d"  | "1" (match) "A" (NO match) "!" (NO match)

# \D                 | Matches a non-digit         | "\D"  | "A" (match) "!" (Match) "_" (match) "1" (NO match)

# \w               | matches a word character      | "\w"  | "1" (match) "A" (match) "_" (match) "!" (NO match) " " (no match)
#                    (letter, digit, underscore)

# \W              | Matches ANY non-word character | "\W"   | "!" (match) " " (match) "1" (NO match) "A" (NO match)

# \s              | Matches any whitespace char    | "\s"   | " " (match) "!" (NO match) "A" (No match)

# \S              | matches any NON-whitespace char | "\S" | "1" (match) "A" (match) "_" (match) "!" (match) " " (NO MATCH)

# [...] CHARACTER SET | Matches any chars inside brackets | "[A-C]" | "A" "B" "C" (all would match)
#                     | can specify rangs of chars also   |         |  "D" (NO match) "E" (NO match)


# [^...] NEGATIVE    | Matches anything NOT inside        | "[^C-E]" | "A" "B" (both match)  "C" (no match) "D" (no match)   
#     Character Set  | the brackets                       |          | "E"(no match)


# . WILDCARD         | WILDCARD: Matches any character    | "."     | "1",  "A",  "_",  "!",  " " (matches ALL of those)
#                    | except a newline

#   *         | matches 0 or MORE times       |    "ca*t" | "ct", "cat", "caat", "caaat" (matches ALL of those)

#     +        | Matches 1 or MORE times      |    "ca+t" | "cat" "caat" "caaat" (matches ALL of those)  "ct" (DOES NOT MATCH)

#     ?        | Matches 0 OR 1 time          |   "ca?t"  | "ct" "cat" (MATCH)    "caat" "caaat" (NO MATCH)

#     {#}      | Matches a specific number of times | "ca{2}t" | "caat" (MATCH) "ct", "cat", "caaat" (NO MATCH)

#     {#,}     | Matches at LEAST a specifc # of times | "ca{2,}t" | "caat" "caaat" "caaaat" (MATCH) "ct" "cat" (NO MATCH)

#     {#,#}    | Matches within a specific RANGE of times | "ca{2,3}t" | "caat" "caaat" (MATCH) "ct" "cat" "caaaaat" (NO MATCH)

#     | ALTERNATION | Matches either the expression before or after | "cat|dog" | "cat" "dog" (MATCH) "bird" (NO MATCH)

#   ^ Caret     | Start of the string |         "^cat" | "cat" "catsup" (MATCH) "concatenate" "kitty-cat" (NO MATCH)

#   $ Dollar sign | END of the string |         "cat$" | "cat" "kitty-cat" (MATCH) "catsup" "concatenate" (NO MATCH)

In [ ]:
###### 8.3.10 ###### PARSE THE BOX OFFICE DATA ##### 8.3.10 ##### 8.3.10 ###############################################

In [ ]:
# Two mains form that the box office data was written in: 
# "$123.4 million" and "$123,456,789"

In [ ]:
# Create the first form
#
# Need to have our pattern match string to include 6 elements in following order.
# 1. A dollar sign \\ 2. An arbitary (but non-zero) number of digits \\ 3. An optional decimal point
# 4. An arbitary (but possibly zero) number of more digits \\ 5. A space (maybe more than one)
# 6. the world "million" or "billion"

# translate those rules into a regular expression, step by step.

In [ ]:
# STEP 1: Start with dollar sign

# Remember that the dollar sign ($) is a special character in  REGULAR EXPRESSIONS, so need to escape it.

    "\$"

In [3]:
# STEP 2: Add an arbitary (but non-zero) number of digits.

# add the \d character to specify digits ONLY, and the "+" modifier to capture one more digits.  So far,
      "\$\d+"

In [ ]:
# STEP 3: Add an optional decimal point.

# Decimal point is a special character, so  it needs to be escaped with a \ (backslash)
# since the decimal point is optional, add a QUESTION Mark (?) after it.
        "\$\d+\.?"

In [ ]:
# STEP 4: Add an arbitary (but possibly zero) number of more digits

# Once again, use the \d character to specify digits ONLY, but now with the "*" modifier b/c there may be
# no more digits after the decimal point.
        "\$\d+\.?\d*"

In [ ]:
# STEP 5: Add a space (maybe more than one)

# Now use the \s character to match WHITESPACE characters.
# just to be safe, we'll match any number of whitespace characters using the "*" modifier

      "\$\d+\.?\d*\s*"

In [ ]:
# STEP 6: Add the world "million" OR "billion"

# Since million and billion only differ by one letter, can match it with a character set  
# for the FIRST LETTER. Specify character sets wtih SQUARE BRACKETS [] 
# So, add: "[mb]illion" to the end of the string.

        "\$\d+\.?\d*\s*\[mb]illion"

In [61]:
# Create a variable to hold the string

form_one = r'\$\d+\.?\d*\s*[mb]illion'

In [62]:
# To count up how many box office values match our first form,
# use the STR.CONTAINS() method on BOX_OFFICE.

# to ignore whether letters are uppercase or lowercase, add an argument called *flags*
# set it squal to re.IGNORECASE.

# finally, we can call the sum() method to count up the total number that return true.

box_office.str.contains(form_one, flags= re.IGNORECASE).sum()

# output - 3,896 box office values that match the form "$123.4 million/billion"

3896

In [ ]:
################## CREATE THE SECOND FORM ############# 8.3.10

In [ ]:
# Looking to match the numbers of our second form: "$123,456,789"

# need our pattern match string to include following elements:

# 1. A dollar sign 

# 2. A group of one to three digits

# 3. At least one group starting with a comma and followed by *exactly* three digits.

In [ ]:
# SECOND FORM : STEP 1 : Start with the dollar sign

"\$"

In [ ]:
# SECOND FORM : STEP 2 : Add a group of one to three digits

# use the \d character for DIGITS, but modify w/ curly brackets {} to only match ONE through three repetitions.

"\${1,3}"

In [ ]:
# SECOND FORM : STEP 3 : Match at least one group starting w/ a comma & followed by EXACTLY three digits

# to match a comma and EXACTLY three digits, use the string ",\d{3}"
# to match any repetition of that group, we'll put it inside parentheses
# then put a "+" sign after the ( ): "(,\d{3})+"

# Need to also add the modification to specify that this is a NON-CAPTURING GROUP 
# to do so, insert question mark (?) and colon (:) after the opening parenthesis:
# "(?:,\d{3})+"

"\$\d{1,3}(?:,\d{3})+"

In [63]:
# FORM TWO VARIABLE 
# need to again make it a raw string (r') so python keeps the escaped characters
form_two = r'\$\d{1,3}(?:,\d{3})+'

In [64]:
# use on box_office
box_office.str.contains(form_two, flags = re.IGNORECASE).sum()

# output - 1,544 box office values that match form "$123,456,789"

1544

In [65]:
# COMPARE VALUES IN FORMS

# Most box_office values are described by either form. Now we need to see which ones aren't described by either.
# also, should check to see if some are described by BOTH.

# Create two Boolean Series called: matches_form_one | matches_form_two
# select the box office values that don't match either.

matches_form_one = box_office.str.contains(form_one, flags = re.IGNORECASE)

matches_form_two = box_office.str.contains(form_two, flags = re.IGNORECASE)

In [ ]:
# Which values in box_office don't match either form.

# the following code will throw an error.
box_office[(not matches_form_one) and (not matches_form_two)]

In [ ]:
# Thankfully, Pandas has element-wise logical operators:

#   ~ (tilde) is the element wise negation- "not"

#  & (ampersand) is the element wise logical- "and"

#  | (pipe) is the element wise logical - "or"

In [66]:
# using pandas element-wise logical ops

box_office[(~ matches_form_one) & (~ matches_form_two)]

# output (first 5) 

# 34                         US$ 4,212,828
# 79                              $335.000
# 110                   $4.35-4.37 million
# 130                        US$ 4,803,039
# 600                           $5000 (US)

34                         US$ 4,212,828
79                              $335.000
110                   $4.35-4.37 million
130                        US$ 4,803,039
600                           $5000 (US)
731                         $ 11,146,270
957                             $ 50,004
1070                          35,254,617
1147    $ 407,618 (U.S.) (sub-total) [1]
1446                        $ 11,829,959
1480                          £3 million
1611                            $520.000
1865                        ¥1.1 billion
2032                                 N/A
2091                                $309
2130               US$ 171.8 million [9]
2257                   US$ 3,395,581 [1]
2263            $ 1,223,034 ( domestic )
2347                            $282.175
2638            $ 104,883 (US sub-total)
2665         926,423 admissions (France)
2697      $ 1.7 million (US) (sub-total)
2823                            $414.000
2924                            $621.000
3088           $32 [2] –33.1 million [1]
3631                                 TBA
3859                  $38.9–40.3 million
3879            CN¥3.650 million (China)
4116                          £7,385,434
4123                            $161.000
4261                  $20.7–23.9 million
4306                              $20-30
4492                        $47.7 millon
4561             $45.2k (only in Turkey)
4662                USD$ 8.2 million [2]
5362                   $ 142 million [3]
5447                               £2.56
5784                            413 733$
6013                             Unknown
6145                  $17.5–18.4 million
6234                  $41.8–41.9 million
6369                               $111k
6370                                $588
6593                      less than $372
6829                    $ 41 million [3]
6843                             8 crore
6904                         $6.9 millon
Name: Box office, dtype: object

In [67]:
#### FIX PATTERN MATCHES #### #### FIX PATTERN MATCHES #### #### FIX PATTERN MATCHES #### #### FIX PATTERN MATCHES #### 

# can fix pattern matches to capture more values by addressing those issues:

# 1. some values have spaces in between the dollar sign and the number.

# 2. some values use a period as a thousands seperator, not a comma.

# 3. some values are given as a range

# 4. "million" is somehow, sometimes being mispelled as "millon"

In [ ]:
# 1. some values have spaces in between the dollar sign and the number.

# Add \s* after the dollar signs
# \s matches any WHITESPACE character, and * matches 0 or MORE times.

form_one = r'\$\s*\d+\.?\d*\s*[mb]illion'
form_two = r'\$\s*\d{1,3}(?:,\d{3})+'

In [68]:
# 2. some values use a period as a thousands seperator, not a comma.

# More complex, but doable.  change form_two to allow for either a COMMA OR PERIOD as a thousands seperator:

form_two = r'\$\s*\d{1,3}(?:[,\.]\d{3})+'

# The results will also match values like 1.234 billin, BUT we're trying to change
# raw numbers like $123,456,787. DONT WANT TO CAPTURE ANY VALUES LIKE 1.234 billion,
# so need to ADD a *negative lookahead group* that looks ahead for "million" or "billion"
# after the number and REJECTS the match if it finds those strings.

form_two = r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)'

In [70]:
# 3. some values are given as a RANGE.

# to solve this, we'll search for any strings that start with a dollar sign ($) and end with a hypen (-)
# and then replace it with just a dollar sign using the REPLACE() method.

# the 1st argument in the REPLACE () method is the substring that will be replaced
# the 2nd argument in the REPLACE () method is the string to replace it wtih.
# can use regular expressions in the first argument by sending the PARAMETER regex= True


box_office = box_office.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)